apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-gateway-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-gateway-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "service"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-gateway-clusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-gateway-clusterrole
subjects:
  - kind: ServiceAccount
    name: service-gateway-sa
    namespace: default