apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ingress
  labels:
    app: test-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lts
  template:
    metadata:
      labels:
        app: lts
    spec:
      containers:
        - name: test-ingress
          imagePullPolicy: Never
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8
          ports:
            - containerPort: 22
              name: ssh
            - containerPort: 8888
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: test-ingress
spec:
  type: NodePort
  selector:
    app: lts
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: http
      port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpu-pod-ingress
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: containercloud.xaidc.com
      http:
        paths:
          - path: /instance
            pathType: Prefix
            backend:
              service:
                name: service-gateway-svc
                port:
                  number: 8080